apiVersion: v1
kind: Namespace
metadata:
  name: llmux-middleware
---
# 1. Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: llmux-middleware
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        command: ["redis-server", "--requirepass", "changeme_in_production"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /var/lib/llmux/redis
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: llmux-middleware
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
# 2. PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: llmux-middleware
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: ankane/pgvector:latest
        env:
        - name: POSTGRES_USER
          value: "llmux"
        - name: POSTGRES_PASSWORD
          value: "changeme_in_production"
        - name: POSTGRES_DB
          value: "llmux"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        hostPath:
          path: /var/lib/llmux/postgres
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: llmux-middleware
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
# 3. Qdrant Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: llmux-middleware
spec:
  selector:
    matchLabels:
      app: qdrant
  replicas: 1
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
        - containerPort: 6334
        volumeMounts:
        - name: qdrant-data
          mountPath: /qdrant/storage
      volumes:
      - name: qdrant-data
        hostPath:
          path: /var/lib/llmux/qdrant
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: llmux-middleware
spec:
  selector:
    app: qdrant
  ports:
  - port: 6333
    targetPort: 6333
    name: http
  - port: 6334
    targetPort: 6334
    name: grpc
