# golangci-lint configuration v2
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/llmux/llmux

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
    - bodyclose
    - noctx
  exclusions:
    rules:
      # Exclude test files from errcheck
      - path: _test\.go
        linters:
          - errcheck
          - gocritic
          - bodyclose
          - shadow
      # Exclude bench directory
      - path: bench/
        linters:
          - errcheck
      # Exclude tests directory
      - path: tests/
        linters:
          - errcheck
          - bodyclose
          - shadow
      # Exclude streaming forwarder
      - path: streaming/forwarder\.go
        linters:
          - errcheck
      # Exclude provider implementations
      - path: provider/.*\.go
        linters:
          - errcheck
        text: "Error return value is not checked"
      # Exclude stuttering type names
      - linters:
          - revive
        text: "stutters"

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - io.Copy
        - io.ReadAll
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - (*github.com/goccy/go-json.Encoder).Encode
        - (*encoding/json.Encoder).Encode
        - fmt.Fprintf
        - fmt.Fprint
        - fmt.Fprintln

    govet:
      enable-all: true
      disable:
        - fieldalignment

    misspell:
      locale: US

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
        - paramTypeCombine
        - unnamedResult
        - ifElseChain
        - importShadow

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

output:
  formats:
    text:
      print-linter-name: true
